apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: "MC_rg-dnk-dev-spoke_aksdnkdev_centralus#stakspvfileshare#filesharetest"  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      resourceGroup: "MC_rg-dnk-dev-spoke_aksdnkdev_centralus"
      storageAccount: "stakspvfileshare"
      shareName: "filesharetest"
      server: "stakspvfileshare.privatelink.file.core.windows.net"   ###stakspvctest.privatelink.file.core.windows.net
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
       - dir_mode=0777
       - file_mode=0777
       - uid=0
       - gid=0
       - mfsymlinks
       - cache=strict
       - nosharesock
       - nobrl
       - vers=3.0  # Explicitly set SMB version
       - actimeo=1  # Reduce attribute cache timeout
   
