apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: default
type: Opaque
data:
  azurestorageaccountname: "c3Rha3NwdmN0ZXN0Mg=="
  azurestorageaccountkey: "MVhDMEc5NkpLZnAyWC93T0RzckVmT01hMDNncEMwNDcwaENXalkvRXVLWkszWXJlNHM2b25INHlGbUNVbzgwOFNOY0NRTUUraGVvYStBU3RoK0d4QkE9PQ=="

